# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'my-app' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'AlpsSDK', '~> 0.6'

  # Pods for my-app

  target 'my-appTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'my-appUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
